# Site settings
title: CSS Guidelines
email: harry@csswizardry.com
description: "High-level advice and guidelines for writing sane, manageable, scalable CSS"
baseurl: ""
url: "http://cssguidelin.es"
version: 2.1.0

# Build settings
markdown: kramdown
permalink: pretty
